name: boldcoast
favicon: null
layout_spectrum: 0.658382105641067
typography_spectrum: 0.638575253309682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff6600'
    - '#592300'
    - '#7a7a7a'
  brandStrength: 0.6829733764752746
  lightness: 0.054857830516994
  saturation: 0.5621801083907485
  rhythmicContrast: 0.722497224342078
purpose: []
